### ISSUE TITLE
Bucket name issue for the object storage

### ISSUE THREAD

**Issue by feihugis** [IBM/MAX-Adversarial-Cryptography#2]
Following the instructions in README.md for training the model on WML, there was a bucket name issue as following:

`make_bucket failed: s3://adversarial-crypto-training An error occurred (BucketAlreadyExists) when calling the CreateBucket operation: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.
make_bucket failed: s3://adversarial-crypto-training-results An error occurred (BucketAlreadyExists) when calling the CreateBucket operation: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.
Starting to train ...
FAILED
INVALID_ARGUMENT: Data store bucket 'adversarial-crypto-training' for data store id 'training-data-reference_name' incorrect, there may be a connection problem or credentials do not allow access to the bucket`

It seems to be caused by the duplicated bucket name in the `run.sh` script. However, if I manually change the bucket name, another issue cames out as following:

`make_bucket: adversarial-crypto-training-123
make_bucket: adversarial-crypto-training-results-123
Starting to train ...
FAILED
INVALID_ARGUMENT: Data store bucket 'adversarial-crypto-training' for data store id 'training-data-reference_name' incorrect, there may be a connection problem or credentials do not allow access to the bucket`.

For this issue, I manually update the bucket name for `training_data_reference` and `training_results_reference` in `training-runs.yml` to be same as what I changed in `run.sh`. Then the model training could work on WML.

**Comment by xwu0226** [comment]
@Luciano Resende who can help you look into this issue?

**Comment by feihugis** [comment]
@xwu0226, this issue is being fixed at PR #9 by @djalova .

**Comment by xwu0226** [comment]
➤ Luciano Resende commented:

I have added some feedback to the PR with what I had in mind previously.
